CREATE OR REPLACE DATABASE OUR_FIRST_DB;
 
 
CREATE OR REPLACE STORAGE INTEGRATION azure_integration

TYPE=EXTERNAL_STAGE

STORAGE_PROVIDER=AZURE

ENABLED=TRUE

AZURE_TENANT_ID='8c7d1dfe-bbc5-4936-9f8b-e361c5dc3590'

STORAGE_ALLOWED_LOCATIONS=('azure://snowflakeaccount1903.blob.core.windows.net/json',

'azure://snowflakeaccount1903.blob.core.windows.net/csv');
 
 
DESC STORAGE INTEGRATION azure_integration;
 
 
CREATE OR REPLACE FILE FORMAT OUR_FIRST_DB.PUBLIC.FILE_FORMAT_AZURE

TYPE=CSV 

FIELD_DELIMITER=','

SKIP_HEADER=1;
 
 
CREATE OR REPLACE STAGE OUR_FIRST_DB.PUBLIC.AZURE_STAGE

STORAGE_INTEGRATION=azure_integration

URL='azure://snowflakeaccount1903.blob.core.windows.net/csv'

file_format=file_format_azure;
 
 
LIST @OUR_FIRST_DB.PUBLIC.AZURE_STAGE;
 
 
CREATE OR REPLACE TABLE HAPPINESS(

COUNTRY_NAME VARCHAR,

REGIONAL_INDICATOR VARCHAR, 

LADDER_SCORE NUMBER(4,3),

STANDARD_ERROR NUMBER(4,3),

UPPERWHISKER NUMBER(4,3),

LOWERWHISKER NUMBER(4,3),

LOGGED_GDP NUMBER(5,3),

SOCIAL_SUPPORT NUMBER(4,3),

HEALTHY_LIFE_EXPECTANCY NUMBER(5,3),

FREEDOM_TO_MAKE_LIFE_CHOICES NUMBER(4,3),

GENEROSITY NUMBER(4,3),

PERCEPTIONS_OF_CORRUPTION NUMBER(4,3),

LADDER_SCORE_IN_DYSTOPIA NUMBER(4,3),

EXPLAINED_BY_LOG_GDP_PER_CAPITA NUMBER(4,3),

EXPLAINED_BY_SOCIAL_SUPPORT NUMBER(4,3),

EXPLAINED_BY_HEALTHY_LIFE_EXPECTANCY NUMBER(4,3),

EXPLAINED_BY_FREEDOM_TO_MAKE_LIFE_CHOICES NUMBER(4,3),

EXPLAINED_BY_GENEROSITY NUMBER(4,3),

EXPLAINED_BY_PERCEPTIONS_OF_CORRUPTION NUMBER(4,3),

DYSTOPIA_RESIDUAL NUMBER(4,3));
 
COPY INTO OUR_FIRST_DB.PUBLIC.HAPPINESS 

FROM @OUR_FIRST_DB.PUBLIC.AZURE_STAGE;
 
SELECT * FROM OUR_FIRST_DB.PUBLIC.HAPPINESS;
 